name: Continuous Deployment
 
on: 
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ec2-108-137-6-31.ap-southeast-3.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: 22
